language: java
jdk:
  - openjdk8
services:
  - mysql
test:
  adapter: mysql
  database: northwind
  username: root
  password: password
  encoding: utf8
before_install:
#  - sudo apt-get update
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

cache:
  directories:
    - $HOME/.m2