language: java
services:
  - mysql
test:
  adapter: mysql2
  database: northwind
  username: travis
  encoding: utf8
before_install:
  - sudo apt-get update
  - mysql -e 'CREATE DATABASE NOT EXISTS northwind;'