language: java
jdk:
  - openjdk8
services:
  - mysql
test:
  adapter: mysql
  database: northwind
  username: root
  password: password
  encoding: utf8
before_install:
#  - sudo apt-get update
before_script:
  - mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password'"

cache:
  directories:
    - $HOME/.m2