language: java
jdk:
  - openjdk8
services:
  - mysql
test:
  adapter: mysql
  database: northwind
  username: root
  password: password
  encoding: utf8
before_install:
#  - sudo apt-get update

cache:
  directories:
    - $HOME/.m2