language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
services:
  - mysql
test:
  adapter: mysql2
  database: northwind
  username: travis
  encoding: utf8
before_install:
  - sudo apt-get update

