language: java
jdk:
  - openjdk8
services:
  - mysql
test:
  adapter: mysql2
  database: northwind
  username: root
  password: password
  encoding: utf8
before_install:
  - sudo apt-get update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS northwind;'
