insert into categories (category_name, description, picture) values ('Books', 'challenge', 'http://dummyimage.com/125x217.bmp/5fa2dd/ffffff');
insert into categories (category_name, description, picture) values ('Baby', 'toolset', 'http://dummyimage.com/134x239.jpg/cc0000/ffffff');
insert into categories (category_name, description, picture) values ('Jewelery', 'real-time', 'http://dummyimage.com/190x140.png/5fa2dd/ffffff');
insert into categories (category_name, description, picture) values ('Toys', 'Robust', 'http://dummyimage.com/111x235.jpg/5fa2dd/ffffff');
insert into categories (category_name, description, picture) values ('Grocery', '5th generation', 'http://dummyimage.com/229x177.bmp/5fa2dd/ffffff');
insert into categories (category_name, description, picture) values ('Toys', 'Phased', 'http://dummyimage.com/164x174.bmp/ff4444/ffffff');
insert into categories (category_name, description, picture) values ('Music', 'needs-based', 'http://dummyimage.com/189x223.png/dddddd/000000');
insert into categories (category_name, description, picture) values ('Movies', 'customer loyalty', 'http://dummyimage.com/121x136.bmp/cc0000/ffffff');
insert into categories (category_name, description, picture) values ('Movies', 'Enhanced', 'http://dummyimage.com/163x158.png/ff4444/ffffff');
insert into categories (category_name, description, picture) values ('Movies', 'Open-source', 'http://dummyimage.com/231x232.bmp/5fa2dd/ffffff');
insert into categories (category_name, description, picture) values ('Electronics', 'Reverse-engineered', 'http://dummyimage.com/170x104.bmp/dddddd/000000');
insert into categories (category_name, description, picture) values ('Automotive', 'capacity', 'http://dummyimage.com/142x246.png/ff4444/ffffff');
insert into categories (category_name, description, picture) values ('Movies', 'initiative', 'http://dummyimage.com/179x232.png/cc0000/ffffff');
insert into categories (category_name, description, picture) values ('Industrial', 'Polarised', 'http://dummyimage.com/211x107.jpg/ff4444/ffffff');
insert into categories (category_name, description, picture) values ('Shoes', 'attitude-oriented', 'http://dummyimage.com/107x243.jpg/5fa2dd/ffffff');
insert into categories (category_name, description, picture) values ('Electronics', 'Stand-alone', 'http://dummyimage.com/147x194.jpg/dddddd/000000');
insert into categories (category_name, description, picture) values ('Movies', 'superstructure', 'http://dummyimage.com/224x137.jpg/dddddd/000000');
insert into categories (category_name, description, picture) values ('Industrial', 'discrete', 'http://dummyimage.com/152x206.jpg/dddddd/000000');
insert into categories (category_name, description, picture) values ('Movies', 'system engine', 'http://dummyimage.com/160x214.jpg/5fa2dd/ffffff');
insert into categories (category_name, description, picture) values ('Music', 'homogeneous', 'http://dummyimage.com/121x212.jpg/dddddd/000000');
